package be.jimsa.iotproject.utility.constant;

public class ProjectConstants {

    private ProjectConstants() {
    }



    public static final int PUBLIC_ID_LENGTH = 64;

    public static final String EXCEPTION_REGEX = "%s %s";
    public static final String EXCEPTION_MESSAGE = "message";
    public static final String EXCEPTION_PATH = "path";
    public static final String EXCEPTION_BAD_FORMAT_MESSAGE = "Bad format of: ";
    public static final String EXCEPTION_RESOURCE_ALREADY_EXIST_MESSAGE = "The resource already exists: ";
    public static final String EXCEPTION_NULL_MESSAGE = "null: ";
    public static final String EXCEPTION_INTERNAL_SERVICE_MESSAGE = "Internal service error: ";

    public static final String PROJECT_ITEM_NAME = "name";
    public static final String PROJECT_ITEM_TYPE = "type";
    public static final String PROJECT_ITEM_PUBLIC_ID = "public_id";
    public static final String PROJECT_NAME = "project";
    public static final String PROJECT_CAST = "casting";

    public static final String VALIDATION_PAGE_POSITIVE_INTEGER = "page must be a positive number";
    public static final String VALIDATION_PAGE_DEFAULT_VALUE = "1";
    public static final String VALIDATION_SIZE_POSITIVE_INTEGER = "size must be a positive number";
    public static final String VALIDATION_SIZE_DEFAULT_VALUE = "10";

    public static final String VALIDATION_SORT_FIELD = "sort_field";
    public static final String VALIDATION_SORT_FIELD_PATTERN_MESSAGE = "sort field must be 'name' or 'type'";
    public static final String VALIDATION_SORT_FIELD_PATTERN = "name|type";
    public static final String VALIDATION_SORT_FIELD_DEFAULT_VALUE = "name";

    public static final String VALIDATION_SORT_DIRECTION = "sort_direction";
    public static final String VALIDATION_SORT_DIRECTION_PATTERN_MESSAGE = "sort direction must be 'asc' or 'desc'";
    public static final String VALIDATION_SORT_DIRECTION_PATTERN = "asc|desc";
    public static final String VALIDATION_SORT_DIRECTION_DEFAULT_VALUE = "asc";

    public static final String VALIDATION_PUBLIC_ID = "public_id";
    public static final String VALIDATION_PUBLIC_ID_PATTERN = "^[A-Za-z0-9-_]+$";
    public static final String VALIDATION_PUBLIC_ID_PATTERN_MESSAGE = "public_id must only contain A-Z, a-z, 0-9, hyphen (-), and underscore (_)";
    public static final String VALIDATION_PUBLIC_ID_SIZE_MESSAGE = "public_id's length must be between 32 and 512 characters";
    public static final String VALIDATION_PUBLIC_ID_NULL_MESSAGE = "can not send a public_id field, it's a read-only field generated by the system";
    public static final String VALIDATION_PUBLIC_ID_NOT_EMPTY_MESSAGE = "public_id can not be empty";
    public static final String VALIDATION_PUBLIC_ID_NOT_BLANK_MESSAGE = "public_id can not be blank";
    public static final int VALIDATION_PUBLIC_ID_MIN = 32;
    public static final int VALIDATION_PUBLIC_ID_MAX = 512;

    public static final String VALIDATION_NAME_PATTERN = "^(?!\\s*$)(?=.{4,100}$).*$";
    public static final String VALIDATION_NAME_NOT_EMPTY_MESSAGE = "name can not be empty";
    public static final String VALIDATION_NAME_NOT_BLANK_MESSAGE = "name can not be blank";
    public static final String VALIDATION_NAME_SIZE_MESSAGE = "name's length must be between 4 and 50 characters";
    public static final int VALIDATION_NAME_MIN = 4;
    public static final int VALIDATION_NAME_MAX = 50;

    public static final String VALIDATION_TYPE_PATTERN = "^(?!\\s*$)(?=.{4,100}$).*$";
    public static final String VALIDATION_TYPE_NOT_EMPTY_MESSAGE = "type can not be empty";
    public static final String VALIDATION_TYPE_NOT_BLANK_MESSAGE = "type can not be blank";
    public static final String VALIDATION_TYPE_SIZE_MESSAGE = "type's length must be between 4 and 100 characters";
    public static final int VALIDATION_TYPE_MIN = 4;
    public static final int VALIDATION_TYPE_MAX = 100;


}
